version: "3.9"
services:
  cnn-model:
    image: fast-food-model:v1-xception
  gateway:
    image: fast-food-gateway:001
    environment:
      - TF_SERVING_HOST=clothing-model:8500
    ports:
      - "9696:9696"